# Generated by Django 5.2.8 on 2025-12-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_address',
            field=models.TextField(blank=True, null=True, verbose_name='Branch Address'),
        ),
    ]
