# Generated by Django 5.2.8 on 2026-04-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='payroll_of',
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Aadhar No'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Others', 'Others')], max_length=10, null=True, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_mobile1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Emergency Contact Mobile No 1'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_mobile2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Emergency Contact Mobile No 2'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_name1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact Name 1'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_name2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact Name 2'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_relation1',
            field=models.CharField(blank=True, choices=[('Spouse', 'Spouse'), ('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Emergency Contact Relation 1'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_relation2',
            field=models.CharField(blank=True, choices=[('Spouse', 'Spouse'), ('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Emergency Contact Relation 2'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Employee Code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esic_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ESIC No'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_as_per_bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name As Per Bank Record'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PAN No'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Passport'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Personal Email ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_mobile',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Personal Mobile No'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PF No'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='present_address',
            field=models.TextField(blank=True, null=True, verbose_name='Present Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Salary Account Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salutation',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Salutation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uan_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Universal Account No. (UAN)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='voter_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Voter ID'),
        ),
    ]
