# Generated by Django 5.2.8 on 2025-12-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattachment',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
