# Generated by Django 5.2.8 on 2025-12-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('InActive', 'inactive')], default='active', max_length=50),
        ),
    ]
