# Generated by Django 5.2.8 on 2025-12-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_employeeattachment_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattachment',
            name='file_name',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('resume', 'Resume'), ('offer_letter', 'Offer Letter')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offboarding',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to='offboarding/certificates/', verbose_name='Experience Certificate'),
        ),
    ]
