# Generated by Django 5.2.8 on 2026-01-27 09:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_leavebalance_closing_balance_leavebalance_compoff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceConfigurable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Late Present', 'Late Present'), ('Half Day', 'Half Day'), ('Absent', 'Absent')], default='Absent', max_length=20)),
                ('count', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('late', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'date'], name='website_att_employe_49b444_idx'), models.Index(fields=['date'], name='website_att_date_c4033a_idx')],
            },
        ),
    ]
