# Generated by Django 5.2.8 on 2025-12-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_branch_branch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=21, max_length=15, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
