# Generated by Django 5.2.8 on 2026-04-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_employee_payroll_of_alter_employee_aadhar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_mobile2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Emergency Contact Mobile No 2'),
        ),
    ]
