# Generated by Django 5.2.8 on 2025-12-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_branch_branch_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Blood Group'),
        ),
    ]
