# Generated by Django 5.2.8 on 2025-12-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_employeeattachment_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offboarding',
            name='relieving_letter',
            field=models.FileField(blank=True, null=True, upload_to='offboarding/relieving_letters/', verbose_name='Relieving Letter'),
        ),
    ]
