# Generated by Django 5.2.8 on 2025-12-05 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_employee_blood_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEmploymentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='previous_employment_docs/')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='website.previousemployment')),
            ],
        ),
    ]
