# Generated by Django 5.2.8 on 2026-01-28 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_attendanceconfigurable'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='financial_year_start_month',
            field=models.PositiveIntegerField(default=4, help_text='Financial year start month (1=January, 4=April, etc.)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
