# Generated by Django 5.2.8 on 2025-12-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_company_email_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='offboarding',
            name='fnf_documents',
            field=models.FileField(blank=True, upload_to='offboarding/fnf/', verbose_name='FNF Document'),
        ),
    ]
