# Generated by Django 5.2.8 on 2025-12-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_offboarding_fnf_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoffrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
