# Generated by Django 5.2.8 on 2025-12-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_offboarding_fnf_documents'),
        ('website', '0004_previousemploymentattachment'),
    ]

    operations = [
    ]
