# Generated by Django 5.2.8 on 2025-12-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_leavebalance_compoff'),
        ('website', '0004_alter_offboarding_relieving_letter'),
    ]

    operations = [
    ]
