# Generated by Django 5.2.8 on 2026-01-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_payrollsettings_financial_year_start_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='period_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='period_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
