# Generated by Django 5.0.4 on 2026-04-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_payrollsettings_weekend_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='late_marks_affect_lwp',
            field=models.BooleanField(default=True, help_text='If unchecked, late marks will never deduct from leave balance / cause LWP, regardless of count.'),
        ),
    ]
