# Generated by Django 5.2.8 on 2025-12-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_merge_20251229_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='shift',
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Shift End Time'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Shift Start Time'),
        ),
    ]
