# Generated by Django 5.2.8 on 2026-02-05 05:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_leavebalance_period_from_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_calendars', to='website.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='HolidayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type_category', models.CharField(choices=[('national', 'National Holiday'), ('regional', 'Regional/State Holiday'), ('company', 'Company Holiday'), ('emergency', 'Emergency Holiday'), ('other', 'Other')], default='national', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#2196F3', help_text='Hex color for calendar display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Holiday Types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['type_category'], name='website_hol_type_ca_7db354_idx')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('declared', 'Declared'), ('optional', 'Optional'), ('emergency', 'Emergency')], default='declared', max_length=20)),
                ('is_national', models.BooleanField(default=False, help_text='True = all branches get this')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('holiday_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='website.holidaycalendar')),
                ('holiday_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.holidaytype')),
            ],
            options={
                'ordering': ['holiday_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyEarnedLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('earned_leaves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_earned_leaves', to='website.payrollsettings')),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
        migrations.CreateModel(
            name='HalfDayScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_date', models.DateField()),
                ('scenario_type', models.CharField(choices=[('rain_closure', 'Rain/Flood Closure'), ('election_day', 'Election Day'), ('emergency_closure', 'Emergency Closure'), ('office_maintenance', 'Office Maintenance'), ('safety_emergency', 'Safety Emergency'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(help_text='e.g., Heavy rain, Election voting')),
                ('credit_count', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Count: 0.5=half day, 1.0=full day', max_digits=3)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_half_day_scenarios', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='half_day_scenarios', to='website.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scenario_date'],
                'indexes': [models.Index(fields=['branch', 'scenario_date'], name='website_hal_branch__21bfdb_idx'), models.Index(fields=['is_approved', 'scenario_date'], name='website_hal_is_appr_7f6ba9_idx')],
                'unique_together': {('branch', 'scenario_date')},
            },
        ),
        migrations.AddIndex(
            model_name='holidaycalendar',
            index=models.Index(fields=['branch', 'year'], name='website_hol_branch__9ad3c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holidaycalendar',
            unique_together={('branch', 'year')},
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['holiday_calendar', 'holiday_date'], name='website_hol_holiday_a906c7_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['holiday_date'], name='website_hol_holiday_e35dbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('holiday_calendar', 'holiday_date')},
        ),
        migrations.AddIndex(
            model_name='monthlyearnedleaves',
            index=models.Index(fields=['payroll_settings', 'year', 'month'], name='website_mon_payroll_818fcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyearnedleaves',
            unique_together={('payroll_settings', 'month', 'year')},
        ),
    ]
