# Generated by Django 5.2.8 on 2025-12-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_employee_shift_employee_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattachment',
            name='other_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeattachment',
            name='file_name',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('resume', 'Resume'), ('offer_letter', 'Offer Letter'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
