# Generated by Django 5.0.4 on 2026-04-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_add_late_marks_affect_lwp'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='lwp_overridden',
            field=models.BooleanField(default=False, help_text='If True, LWP was manually set and recalculation will preserve it.'),
        ),
    ]
