# Generated by Django 5.2.8 on 2025-12-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_compoffrequest_rejection_reason'),
        ('website', '0006_leaveapplication'),
    ]

    operations = [
    ]
