# Generated by Django 5.2.8 on 2026-02-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_holidaycalendar_holidaytype_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='half_day_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.halfdayscenario'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.holiday'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Late Present', 'Late Present'), ('Half Day', 'Half Day'), ('Absent', 'Absent'), ('Holiday', 'Holiday'), ('Weekend', 'Weekend'), ('Present (Half-Day)', 'Present (Half-Day)')], default='Absent', max_length=20),
        ),
    ]
