# Generated by Django 5.2.8 on 2026-02-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_attendance_half_day_scenario_attendance_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='branch_specific_holidays',
            field=models.BooleanField(default=True, help_text='When True, regional holidays only apply to their specific branch. When False, all holidays apply to all branches.'),
        ),
    ]
