# Generated by Django 5.2.8 on 2026-01-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_merge_20260105_1047'),
        ('website', '0007_employeeattachment_other_file_name_and_more'),
    ]

    operations = [
    ]
