# Generated by Django 5.2.8 on 2025-12-09 04:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_merge_20251209_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancemaster',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='advancemaster',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='advancemaster',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='advancemaster',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='advancemaster',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='advancemaster',
            name='advance_amount',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancemaster',
            name='default_months',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancemaster',
            name='outstanding_amount',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancemaster',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='advancemaster',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='website.advancemaster')),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_month', models.DateField()),
                ('scheduled_amount', models.PositiveIntegerField()),
                ('paid_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='website.advancemaster')),
            ],
            options={
                'ordering': ['due_month'],
            },
        ),
        migrations.DeleteModel(
            name='AdvanceInstallment',
        ),
    ]
