# Generated by Django 5.2.8 on 2025-12-09 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_created_on_advancemaster_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.company')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.IntegerField()),
                ('present_days', models.FloatField()),
                ('leave_days', models.FloatField()),
                ('leave_adjust', models.FloatField(default=0)),
                ('basic_processed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hra_processed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sp_allowance_processed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allowance1_processed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allowance2_processed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stat_bonus_processed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_processed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esic_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='website.payrollrun')),
            ],
        ),
    ]
