# Generated by Django 5.2.8 on 2025-12-10 06:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_payrollrun_payrollrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrecord',
            options={'ordering': ['employee__first_name']},
        ),
        migrations.AlterModelOptions(
            name='payrollrun',
            options={'ordering': ['-month']},
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='advance_deducted',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='leave_days',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='net_pay',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='total_deduction',
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='advance_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='allowance1_pm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='allowance2_pm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='basic_pm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='calculation_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='employee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='esic_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='esic_employer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='gratuity_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='gross_ctc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='hra_pm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='leave_taken',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='manual_override',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='pf_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='pf_employer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='sp_allowance_pm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='stat_bonus_pm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='allowance1_processed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='allowance2_processed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='basic_processed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='esic_employee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='gross_processed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='hra_processed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='leave_adjust',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='pf_employee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='present_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='sp_allowance_processed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='stat_bonus_processed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.company'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='month',
            field=models.DateField(help_text='Use the first day of month to represent the payroll month (e.g. 2025-12-01)'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20),
        ),
    ]
