# Generated by Django 5.2.8 on 2026-01-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_employee_user_alter_employee_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
