# Generated by Django 5.2.8 on 2025-12-10 08:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_payrollrecord_options_alter_payrollrun_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='advance_deduction',
            new_name='advance',
        ),
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='esic_applicable',
            new_name='opted_for_pf',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='gratuity_applicable',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='pf_deducted',
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='esic_er_cont',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='month_display',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='percent_adjusted',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='pf_er_cont',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='total_gross_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='month',
            field=models.DateField(help_text='First day of month representing payroll month'),
        ),
    ]
