# Generated by Django 5.2.8 on 2026-01-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_employee_force_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Left', 'Left')], default='Active', max_length=50),
        ),
    ]
