# Generated by Django 5.2.8 on 2025-12-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_advance_deduction_payrollrecord_advance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='leave_adjust',
            new_name='leave_without_pay',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='esic_employer',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='esic_er_cont',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='percent_adjusted',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='pf_employer',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='pf_er_cont',
        ),
    ]
