# Generated by Django 5.0.4 on 2026-07-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_halfdayscenario_branch_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceupload',
            name='created_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendanceupload',
            name='errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='attendanceupload',
            name='skipped_count',
            field=models.IntegerField(default=0),
        ),
    ]
