# Generated by Django 5.2.8 on 2025-12-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_merge_20251208_1641'),
        ('website', '0011_rename_advance_deduction_payrollrecord_advance_and_more'),
    ]

    operations = [
    ]
