# Generated by Django 5.0.4 on 2026-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_attendanceupload_created_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status_overridden',
            field=models.BooleanField(default=False, help_text='If True, status/count was manually set (e.g. payroll late-day forgiveness) and calculate_status() will preserve it instead of recomputing from in/out time.'),
        ),
    ]
