# Generated by Django 5.2.8 on 2025-12-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_merge_20251212_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecorrectionrequest',
            name='new_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancecorrectionrequest',
            name='new_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancecorrectionrequest',
            name='old_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancecorrectionrequest',
            name='old_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
