# Generated by Django 5.0.4 on 2026-08-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_attendance_status_overridden'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceupload',
            name='updated_count',
            field=models.IntegerField(default=0),
        ),
    ]
