# Generated by Django 5.0.4 on 2026-08-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_attendanceupload_updated_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='applies_to_all_employees',
            field=models.BooleanField(default=True, help_text='False = only the manually selected employees get this holiday.'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='specific_employees',
            field=models.ManyToManyField(blank=True, help_text="Employees who get this holiday, when 'Applies to all employees' is off.", related_name='specific_holidays', to='website.employee'),
        ),
    ]
