# Generated by Django 5.0.4 on 2026-08-21 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_holiday_applies_to_all_employees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(help_text='e.g. Day Shift, Night Shift', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('shift_start_time', models.TimeField(blank=True, help_text='Optional, for reference only', null=True)),
                ('shift_end_time', models.TimeField(blank=True, help_text='Optional, for reference only', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='website.employee')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employee', 'start_date', 'end_date'], name='website_shi_employe_e65504_idx')],
            },
        ),
    ]
