# Generated by Django 5.0.4 on 2026-08-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_shiftassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='week_off_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text="Overrides the company's default weekly off (e.g. Saturday for night-shift staff instead of the usual Sunday). Leave blank to use the company default.", null=True, verbose_name='Weekly Off Day'),
        ),
    ]
