# Generated by Django 5.0.4 on 2026-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_employee_week_off_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='pf_wage_ceiling',
            field=models.FloatField(default=15000.0, help_text='Statutory PF wage ceiling. Employee/employer PF contribution is PF % of MIN(Basic, this ceiling) — e.g. 15000 x 12% = 1800.'),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='basic_cap',
            field=models.FloatField(default=21000.0, help_text='Ceiling used when deriving Basic from Gross CTC during salary structuring (Basic = MIN(Gross CTC x Basic %, this cap)). Not used for PF.'),
        ),
    ]
