# Generated by Django 5.0.4 on 2026-08-26 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from website.permissions_registry import FEATURES, SEED_GRANTS, SYSTEM_ROLES


def seed_roles_and_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Feature = apps.get_model("website", "Feature")
    RoleFeaturePermission = apps.get_model("website", "RoleFeaturePermission")

    groups = {name: Group.objects.get_or_create(name=name)[0] for name in SYSTEM_ROLES}

    features = {}
    for row in FEATURES:
        feature, created = Feature.objects.get_or_create(key=row["key"], defaults=row)
        features[row["key"]] = feature

    for feature_key, feature in features.items():
        rfp_by_role = {
            name: RoleFeaturePermission.objects.get_or_create(role=group, feature=feature)[0]
            for name, group in groups.items()
        }
        for action in ("view", "edit", "approve"):
            granted = SEED_GRANTS.get((feature_key, action), ())
            for name, rfp in rfp_by_role.items():
                setattr(rfp, f"can_{action}", name in granted)
        for rfp in rfp_by_role.values():
            rfp.save()


def unseed_roles_and_permissions(apps, schema_editor):
    Feature = apps.get_model("website", "Feature")
    # Cascades to RoleFeaturePermission. Deliberately does NOT delete the 4
    # groups themselves -- they may already have real users assigned.
    Feature.objects.filter(key__in=[row["key"] for row in FEATURES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0018_payrollsettings_pf_wage_ceiling_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text="UI grouping header only (e.g. 'Attendance & Scheduling'). Does not affect permission logic.", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('has_view', models.BooleanField(default=True)),
                ('has_edit', models.BooleanField(default=True)),
                ('has_approve', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleFeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='website.feature')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_permissions', to='auth.group')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('role', 'feature')},
            },
        ),
        migrations.RunPython(seed_roles_and_permissions, unseed_roles_and_permissions),
    ]
