# Generated by Django 5.0.4 on 2026-08-28 08:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from website.permissions_registry import FEATURES, SEED_GRANTS, SYSTEM_ROLES

_ANNOUNCEMENTS_FEATURE = next(row for row in FEATURES if row["key"] == "announcements")


def seed_announcements_feature(apps, schema_editor):
    """Register the new 'announcements' Feature + its RoleFeaturePermission
    rows -- migration 0019 already seeded everything else, so this only
    needs to add the one new feature, not re-seed the other 17."""
    Group = apps.get_model("auth", "Group")
    Feature = apps.get_model("website", "Feature")
    RoleFeaturePermission = apps.get_model("website", "RoleFeaturePermission")

    feature, _ = Feature.objects.get_or_create(
        key=_ANNOUNCEMENTS_FEATURE["key"], defaults=_ANNOUNCEMENTS_FEATURE,
    )

    for role_name in SYSTEM_ROLES:
        group, _ = Group.objects.get_or_create(name=role_name)
        rfp, _ = RoleFeaturePermission.objects.get_or_create(role=group, feature=feature)
        for action in ("view", "edit", "approve"):
            granted = SEED_GRANTS.get(("announcements", action), ())
            setattr(rfp, f"can_{action}", role_name in granted)
        rfp.save()


def unseed_announcements_feature(apps, schema_editor):
    Feature = apps.get_model("website", "Feature")
    Feature.objects.filter(key="announcements").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_seed_roles_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for an announcement that never expires on its own.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Leave blank to show this announcement to every company.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='website.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='website.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('announcement', 'user')},
            },
        ),
        migrations.RunPython(seed_announcements_feature, unseed_announcements_feature),
    ]
