# Generated by Django 5.0.4 on 2026-08-28 11:23

from django.db import migrations, models


def backfill_opted_for_esic(apps, schema_editor):
    """New field defaults to False for every already-existing PayrollRecord.
    That's correct for employees whose salary structure has ESIC off, but
    would silently turn ESIC OFF for anyone who actually has it on (the
    opposite of the bug this field exists to fix) if such a record gets
    finalized without first going through Recalculate, which is the only
    other place opted_for_esic gets (re)populated. Backfill it now from
    each record's employee's current salary master instead."""
    PayrollRecord = apps.get_model("website", "PayrollRecord")
    SalaryMaster = apps.get_model("website", "SalaryMaster")

    esic_employee_ids = set(
        SalaryMaster.objects.filter(is_active=True, esic_applicable=True)
        .values_list("employee_id", flat=True)
    )
    if esic_employee_ids:
        PayrollRecord.objects.filter(employee_id__in=esic_employee_ids).update(opted_for_esic=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_add_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='opted_for_esic',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_opted_for_esic, noop_reverse),
    ]
