# Generated by Django 5.0.4 on 2026-08-28 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from website.permissions_registry import FEATURES, SEED_GRANTS, SYSTEM_ROLES

_AUDIT_LOG_FEATURE = next(row for row in FEATURES if row["key"] == "audit_log")


def seed_audit_log_feature(apps, schema_editor):
    """Register the new 'audit_log' Feature + its RoleFeaturePermission
    rows -- migration 0019 already seeded everything else, so this only
    needs to add the one new feature, not re-seed the others."""
    Group = apps.get_model("auth", "Group")
    Feature = apps.get_model("website", "Feature")
    RoleFeaturePermission = apps.get_model("website", "RoleFeaturePermission")

    feature, _ = Feature.objects.get_or_create(
        key=_AUDIT_LOG_FEATURE["key"], defaults=_AUDIT_LOG_FEATURE,
    )

    for role_name in SYSTEM_ROLES:
        group, _ = Group.objects.get_or_create(name=role_name)
        rfp, _ = RoleFeaturePermission.objects.get_or_create(role=group, feature=feature)
        for action in ("view", "edit", "approve"):
            granted = SEED_GRANTS.get(("audit_log", action), ())
            setattr(rfp, f"can_{action}", role_name in granted)
        rfp.save()


def unseed_audit_log_feature(apps, schema_editor):
    Feature = apps.get_model("website", "Feature")
    Feature.objects.filter(key="audit_log").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_payrollrecord_opted_for_esic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('role_created', 'Role created'), ('role_renamed', 'Role renamed'), ('role_deleted', 'Role deleted'), ('role_permissions_updated', 'Role permissions updated'), ('role_assigned', 'Role assigned to employee'), ('salary_created', 'Salary structure created'), ('salary_updated', 'Salary structure updated'), ('payroll_finalized', 'Payroll run finalized'), ('employee_created', 'Employee record created'), ('employee_updated', 'Employee record updated'), ('offboarding_created', 'Offboarding created'), ('offboarding_updated', 'Offboarding updated'), ('offboarding_deleted', 'Offboarding deleted'), ('leave_approved', 'Leave approved'), ('leave_rejected', 'Leave rejected'), ('compoff_approved', 'Comp-off approved'), ('compoff_rejected', 'Comp-off rejected'), ('correction_approved', 'Attendance correction approved'), ('correction_rejected', 'Attendance correction rejected'), ('user_account_created', 'User account created')], db_index=True, max_length=40)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_repr', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='website.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='website.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='website_aud_target__e16165_idx')],
            },
        ),
        migrations.RunPython(seed_audit_log_feature, unseed_audit_log_feature),
    ]
