# Generated by Django 5.0.4 on 2026-08-29 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_add_audit_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='halfdayscenario',
            name='unique_branch_scenario_date',
        ),
        migrations.RemoveConstraint(
            model_name='halfdayscenario',
            name='unique_allbranch_scenario_date',
        ),
        migrations.RemoveConstraint(
            model_name='holiday',
            name='unique_holiday_date',
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='halfdayscenario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='holidaytype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offboarding',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salaryincrement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('role_created', 'Role created'), ('role_renamed', 'Role renamed'), ('role_deleted', 'Role deleted'), ('role_permissions_updated', 'Role permissions updated'), ('role_assigned', 'Role assigned to employee'), ('salary_created', 'Salary structure created'), ('salary_updated', 'Salary structure updated'), ('payroll_finalized', 'Payroll run finalized'), ('employee_created', 'Employee record created'), ('employee_updated', 'Employee record updated'), ('offboarding_created', 'Offboarding created'), ('offboarding_updated', 'Offboarding updated'), ('offboarding_deleted', 'Offboarding deleted'), ('leave_approved', 'Leave approved'), ('leave_rejected', 'Leave rejected'), ('compoff_approved', 'Comp-off approved'), ('compoff_rejected', 'Comp-off rejected'), ('correction_approved', 'Attendance correction approved'), ('correction_rejected', 'Attendance correction rejected'), ('user_account_created', 'User account created'), ('record_archived', 'Record archived'), ('record_restored', 'Record restored'), ('employee_archived', 'Employee archived'), ('employee_restored', 'Employee restored'), ('offboarding_archived', 'Offboarding archived'), ('offboarding_restored', 'Offboarding restored')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Left', 'Left'), ('Archived', 'Archived')], default='Active', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='halfdayscenario',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False), ('is_active', True)), fields=('branch', 'scenario_date'), name='unique_active_branch_scenario_date'),
        ),
        migrations.AddConstraint(
            model_name='halfdayscenario',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True), ('is_active', True)), fields=('scenario_date',), name='unique_active_allbranch_scenario_date'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('holiday_date',), name='unique_active_holiday_date'),
        ),
    ]
