# Generated by Django 5.0.4 on 2026-09-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_add_salary_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='compoff_overridden',
            field=models.BooleanField(default=False, help_text='If True, Comp Off was manually set and recalculation will preserve it.'),
        ),
    ]
