# Generated by Django 5.0.4 on 2026-09-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_leavebalance_compoff_overridden'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='approved_status',
            field=models.CharField(blank=True, choices=[('Present', 'Full Day (Present)'), ('Late Present', 'Late Present'), ('Half Day', 'Half Day'), ('Absent', 'Absent')], help_text='Status the approver explicitly granted when approving. Blank means the status was derived automatically from the corrected in/out times.', max_length=20, null=True),
        ),
    ]
