# Generated by Django 5.0.4 on 2026-09-03 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_attendancecorrectionrequest_approved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='website.employee', verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportees', to='website.employee', verbose_name='Reporting Person'),
        ),
        migrations.AddField(
            model_name='employee',
            name='use_department_defaults',
            field=models.BooleanField(default=True, help_text='When on, this employee follows whoever is set on their department.', verbose_name="Use department's reporting person & manager"),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Approves above the reporting person. May be the same person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_as_manager', to='website.employee')),
                ('reporting_person', models.ForeignKey(blank=True, help_text='Handles approvals for this department day to day.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_as_reporting_person', to='website.employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='unique_active_department_name'),
        ),
    ]
