# Generated by Django 5.0.4 on 2026-09-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_seed_department_management_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('role_created', 'Role created'), ('role_renamed', 'Role renamed'), ('role_deleted', 'Role deleted'), ('role_permissions_updated', 'Role permissions updated'), ('role_assigned', 'Role assigned to employee'), ('salary_created', 'Salary structure created'), ('salary_updated', 'Salary structure updated'), ('payroll_finalized', 'Payroll run finalized'), ('employee_created', 'Employee record created'), ('employee_updated', 'Employee record updated'), ('offboarding_created', 'Offboarding created'), ('offboarding_updated', 'Offboarding updated'), ('offboarding_deleted', 'Offboarding deleted'), ('leave_approved', 'Leave approved'), ('leave_rejected', 'Leave rejected'), ('compoff_approved', 'Comp-off approved'), ('compoff_rejected', 'Comp-off rejected'), ('correction_approved', 'Attendance correction approved'), ('correction_rejected', 'Attendance correction rejected'), ('user_account_created', 'User account created'), ('record_created', 'Record created'), ('record_updated', 'Record updated'), ('record_archived', 'Record archived'), ('record_restored', 'Record restored'), ('employee_archived', 'Employee archived'), ('employee_restored', 'Employee restored'), ('offboarding_archived', 'Offboarding archived'), ('offboarding_restored', 'Offboarding restored')], db_index=True, max_length=40),
        ),
    ]
