# Generated by Django 5.0.4 on 2026-09-03 10:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='full_day_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='Hours that make a full working day. Also the duty length lateness is measured against.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.50')), django.core.validators.MaxValueValidator(Decimal('24.00'))], verbose_name='Full day hours'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='half_day_count',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text="Day-count a Half Day is worth for payroll (0.50 = half a day's pay).", max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Half Day credit'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='half_day_min_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.50'), help_text='Work at least this many hours for a Half Day. Below this the day is Absent.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('24.00'))], verbose_name='Half Day from (hours)'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='late_present_min_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.30'), help_text='Work at least this many hours, but short of a full day, to still be credited a full day as Late Present.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('24.00'))], verbose_name='Late Present from (hours)'),
        ),
    ]
