# Generated by Django 5.0.4 on 2026-09-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_payrollsettings_full_day_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='is_mom',
            field=models.BooleanField(default=False, help_text='Raised as a Minutes of Meeting, with call timings and the minutes attached.', verbose_name='Minutes of Meeting'),
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='meeting_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Meeting In-Call Time'),
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='meeting_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Meeting Out-Call Time'),
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='mom_attachment',
            field=models.FileField(blank=True, null=True, upload_to='attendance_corrections/mom/', verbose_name='Minutes of Meeting Attachment'),
        ),
    ]
