# Generated by Django 5.0.4 on 2026-09-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_attendancecorrectionrequest_is_mom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='has_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolefeaturepermission',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
    ]
