# Generated by Django 5.0.4 on 2026-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_employeeimportupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeimportupload',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
