# Generated by Django 5.0.4 on 2026-09-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_employeeimportupload_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoffrequest',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
    ]
