# Generated by Django 5.0.4 on 2026-10-06 10:20

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_hr_edits_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.employee_photo_path, verbose_name='Photo'),
        ),
    ]
